secp256k1: enable ellswift module
When running `cargo tarpaulin` (for test coverage) in a project that
depends on this crate, compilation fails with:

```
= note: /usr/bin/ld: /rust-bitcoinconsensus/target/debug/build/bitcoinconsensus-6e1dd1af27ef0a27/out/libbitcoinconsensus.a(0ad13e9c6ad06456-pubkey.o): in function `EllSwiftPubKey::Decode() const':
          /rust-bitcoinconsensus/depend/bitcoin/src/pubkey.cpp:355: undefined reference to `secp256k1_ellswift_decode'
          collect2: error: ld returned 1 exit status

```

I am not sure why it's not a problem when compiling using `cargo
test`, but the code does reference this function, so the module should
be enabled.